[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
from = "/share"
to = "/share.html"
status = 200
force = true


[[headers]]
  for = "/*"
  [headers.values]
  Service-Worker-Allowed = "/"
