[build]
  publish = "."
  command = "npm ci --prefix netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["linkedom", "cheerio"]

[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# SPA-Fallbacks
[[redirects]]
  from = "/share"
  to = "/share.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200