[build]
  publish = "build"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["linkedom", "cheerio"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"