[build]
  publish = "."
  environment = { NODE_VERSION = "20.11.1" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cheerio","linkedom"]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/share"
  to = "/share.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200