[build]
  command = "npm --prefix netlify/functions ci"
  publish = "."

[build.environment]
  NODE_VERSION = "20.15.1"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"